version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      zk_id: "1"
    ports:
      - "2181:2181"
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:5.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis
    ports:
      - "6379:6379"
#Just for local
#docker-compose -f docker-compose-dev.yml up
#docker-compose -f docker-compose-dev.yml exec kafka kafka-topics --delete --bootstrap-server localhost:9092 --topic example-topic
#docker-compose -f docker-compose-dev.yml exec kafka kafka-topics --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic example-topic
#docker-compose -f docker-compose-dev.yml exec kafka kafka-console-producer --broker-list localhost:9092 --topic example-topic
